import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { alkalami, roboto_regular, roboto_bold } from "@/utils/fonts";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { QCProvider } from "@/providers/queryClientProvider";
import { ThemeProvider } from "@/components/theme-provider"
import { AppSidebar } from "@/components/app-sidebar"
import React from "react";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Curriculum",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${alkalami.variable} ${roboto_regular.variable} ${roboto_bold.variable} antialiased`}
      >
        <QCProvider>
          <SidebarProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <AppSidebar />
              <main className="flex flex-col w-full">
                <SidebarTrigger />
                <div className="flex flex-col items-center justify-center sm:justify-start min-h-[calc(100vh-1.75rem)] w-full sm:pt-16 md:pt-36 px-5 pb-5 pt-1">
                  {children}
                </div>
              </main>
            </ThemeProvider>
          </SidebarProvider>
          <ReactQueryDevtools />
        </QCProvider>
      </body>
    </html >
  );
}
